# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'deepwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for deepwork
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Interactable', :path => '../node_modules/react-native-interactable'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport'
    # Add any other subspecs you want to use in your project
  ]

  target 'deepworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'deepwork-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for deepwork-tvOS

  target 'deepwork-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end